{% set name = "piecash" %}
{% set version = "1.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/piecash-{{ version }}.tar.gz
  sha256: 0c23192735133a71c2252ed59fd3bcc505e9d1941f23239795d6fede2bba5612

build:
  number: 0
  noarch: python
  entry_points:
    - piecash = piecash.scripts.export:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - click
    - python >=3.6
    - pytz
    - sqlalchemy >=1.0,<1.4
    - sqlalchemy-utils !=0.36.8
    - tzlocal

test:
  imports:
    - piecash
    - piecash.business
  commands:
    - pip check
    - piecash --help
  requires:
    - pip

about:
  home: https://github.com/sdementen/piecash
  summary: A pythonic interface to GnuCash SQL documents.
  doc_url: https://pythonhosted.org/piecash/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - holymonson
